config/routes.rb
Rails.application.routes.draw do
  resources :atm_maches 
    resources :accounts,only: [:new,]
    resources :transactions
    resources :user_infos
     devise_for :users
      root 'atm_maches#index'
    resources :accounts do
      member do
        get :transaction_list
        get :select_transaction
        get :new_deposit
        post :create_deposit
        get :new_withdrawal
        post :create_withdrawal
      end
    end
        get 'page/home'
  
end

app/models/atm_mach.rb
class AtmMach < ActiveRecord::Base
    geocoded_by :address
   after_validation :geocode, :if => :address_changed?
   
    has_many :transactions
  def show
    session[:atm_no] = @atm_machine.id
  end
  def sort
    scope :sort, -> { order(id: :asc) }
  end
end

app/controllers/atm_maches_controller.rb
class AtmMachesController < ApplicationController
   before_action :set_atm_mach, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, only: [:index]
  # GET /atm_maches
  # GET /atm_maches.json
  def index
    if params[:search].present?
      @atm_machs = AtmMach.near(params[:search], 50, :order => :distance)
    else
    @atm_machs = AtmMach.all
    end
  end

  # GET /atm_maches/1
  # GET /atm_maches/1.json
  def show
     session[:atm_no] = @atm_mach.id

  end

  # GET /atm_maches/new
  def new
    @atm_mach = AtmMach.new
  end

  # GET /atm_maches/1/edit
  def edit
  end

  # POST /atm_maches
  # POST /atm_maches.json
  def create
    @atm_mach = AtmMach.new(atm_mach_params)

    respond_to do |format|
      if @atm_mach.save
        format.html { redirect_to @atm_mach, notice: ' successfully created.' }
        format.json { render :show, status: :created, location: @atm_mach }
      else
        format.html { render :new }
        format.json { render json: @atm_mach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atm_maches/1
  # PATCH/PUT /atm_maches/1.json
  def update
    respond_to do |format|
      if @atm_mach.update(atm_mach_params)
        format.html { redirect_to @atm_mach, notice: ' successfully updated.' }
        format.json { render :show, status: :ok, location: @atm_mach }
      else
        format.html { render :edit }
        format.json { render json: @atm_mach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atm_maches/1
  # DELETE /atm_maches/1.json
  def destroy
    @atm_mach.destroy
    respond_to do |format|
      format.html { redirect_to atm_maches_url, notice: 'successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_atm_mach
      @atm_mach = AtmMach.find(params[:id])
    end

  
    def atm_mach_params
      params.require(:atm_mach).permit( :address)
    end
end

app/helpers/atm_maches_helper.rb
module AtmMachesHelper
end

app/views/atm_maches/_form.html.erb
<%= form_for(@atm_mach) do |f| %>
  <% if @atm_mach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atm_mach.errors.count, "error") %> prohibited this atm_mach from being saved:</h2>

      <ul>
      <% @atm_mach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atm_maches/edit.html.erb
<h1>Editing Atm Mach</h1>

<%= render 'form' %>

<%= link_to 'Show', @atm_mach %> |
<%= link_to 'Back', atm_maches_path %>

app/views/atm_maches/index.html.erb
<!DOCTYPE html>
<html lang="en">
<center><h2> Avalible ATM Locations</h2></center>0
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Casual - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-casual.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
   <tr>
      
      <h2><th>ATM LOCATION</th></h2>
      <th colspan="3"></th>
    </tr>
</head>

<body>

    <div class="brand">Business Casual</div>
    <div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="blog.html">Blog</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="img/slide-1.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="img/slide-2.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="img/slide-3.jpg" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Welcome to</small>
                    </h2>
                    <h1 class="brand-name">Business Casual</h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>By
                            <strong>Start Bootstrap</strong>
                        </small>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Build a website
                        <strong>worth visiting</strong>
                    </h2>
                    <hr>
                    <img class="img-responsive img-border img-left" src="img/intro-pic.jpg" alt="">
                    <hr class="visible-xs">
                    <p>The boxes used in this template are nested inbetween a normal Bootstrap row and the start of your column layout. The boxes will be full-width boxes, so if you want to make them smaller then you will need to customize.</p>
                    <p>A huge thanks to <a href="http://join.deathtothestockphoto.com/" target="_blank">Death to the Stock Photo</a> for allowing us to use the beautiful photos that make this template really come to life. When using this template, make sure your photos are decent. Also make sure that the file size on your photos is kept to a minumum to keep load times to a minimum.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Beautiful boxes
                        <strong>to showcase your content</strong>
                    </h2>
                    <hr>
                    <p>Use as many boxes as you like, and put anything you want in them! They are great for just about anything, the sky's the limit!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->
 <% @atm_machs.each do |atm_mach| %>
      <tr>
      <td><%= atm_mach.address %></td>
      <td><%= link_to 'Select' , atm_mach , class:"btn btn-info"%></td>
      
      </tr>
    <% end %>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

app/views/atm_maches/new.html.erb
<h1>New Atm Mach</h1>

<%= render 'form' %>

<%= link_to 'Back', atm_maches_path %>

app/views/atm_maches/show.html.erb
       <center><strong><h2>ATM Location</h2></strong>
        <h2><%= @atm_mach.address %></h2>
     
<center><% if current_user.user_info.present? %>
     <%=link_to 'Withdrawal', new_withdrawal_account_path(current_user.account), class:"btn btn-info btn-lg" %> &nbsp; 
    <%=link_to  'Add Deposit',  new_deposit_account_path(current_user.account), class:"btn btn-info btn-lg" %> &nbsp; 
     <%= link_to' Update info',edit_user_info_path(current_user.user_info.id,atm_no: @atm_mach.id), class:"btn btn-info btn-lg" %> &nbsp;
     <%=link_to ' transactions',  transaction_list_account_path(current_user.account ),class:"btn btn-info btn-lg"%></center>&nbsp;
    <%else%> 
        <center><%= link_to 'Add Account information',new_user_info_path(atm_no: @atm_mach.id ),class:" col-md-4 col-md-offset-2  btn btn-info btn-lg" %></center>
    <%end%>
<br><br><br><br>
<center><%= image_tag"https://maps.googleapis.com/maps/api/staticmap?size=375x250&sensor=false&zoom=16&markers=#{@atm_mach.latitude}%2C#{@atm_mach.longitude}" %></center>
<center><h3>Nearby ATM_Location</h3></center>
<center><ul>
<% for atm_mach in @atm_mach.nearbys(10) %>
<li><%= link_to atm_mach.address, atm_mach %> (<%= atm_mach.distance.round(2) %> miles)</li>
<% end %>
</ul></center>