config/routes.rb
Rails.application.routes.draw do
  resources :atm_maches 
    resources :accounts,only: [:new,]
    resources :transactions
    resources :user_infos
     devise_for :users
      root 'atm_maches#index'
    resources :accounts do
      member do
        get :transaction_list
        get :select_transaction
        get :new_deposit
        post :create_deposit
        get :new_withdrawal
        post :create_withdrawal
      end
    end
        get 'page/home'
  
end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
  belongs_to :user
  has_one :account
  validates :first_name,:last_name,:city,:state, :phone, :presence => true      
  validates_format_of :phone,:with => /\(?[0-9]{3}\)?-[0-9]{3}-[0-9]{4}/,:message => "- Phone numbers must be in xxx-xxx-xxxx format."
  validates :first_name, uniqueness: { scope: [:last_name, :phone] , message: "or last name should be unique" },case_sensitive: false
  after_create :create_account

  private
    def create_account
      Account.create(user_id: user_id , balance: 0.0)
    end

 mount_uploader :image, ImageUploader
    #validates_format_of :image, :with => %r{\.(jpg|jpeg)$}i, :message => "Only JPG Format"
    validate :image_size_validation
    
    
    def image_size_validation
     errors[:image] << "should be less than 5MB" if image.size > 5.megabytes
    end
   

end

app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  before_action :set_user_info, only: [:show, :edit, :update, :destroy]

  # GET /user_infos
  # GET /user_infos.json
  def index
    @user_infos = UserInfo.all
  end

  # GET /user_infos/1
  # GET /user_infos/1.json
  def show
  end

  # GET /user_infos/new
  def new
      @user_info = UserInfo.new
      session[:atm_no] = params[:atm_no] 
  end

  # GET /user_infos/1/edit
  def edit
    session[:atm_no] = params[:atm_no] 
  end

  # POST /user_infos
  # POST /user_infos.json
  def create
    
  @user_info = UserInfo.new(user_info_params)
  @atm_no = params[:atm_no] 
    respond_to do |format|
      if @user_info.save
        format.html { redirect_to atm_mach_path(session[:atm_no])}
        format.json { render :show, status: :created, location: @user_info }
      else
        format.html { render :new }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_infos/1
  # PATCH/PUT /user_infos/1.json
  def update
    @atm_no = params[:atm_no] 
    respond_to do |format|
      if @user_info.update(user_info_params)
        format.html { redirect_to atm_mach_path(session[:atm_no])}
        format.json { render :show, status: :ok, location: @user_info }
      else
        format.html { render :edit }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_infos/1
  # DELETE /user_infos/1.json
  #def destroy
   # @user_info.destroy
    #respond_to do |format|
     #format.html { redirect_to user_infos_url, notice: 'User info was successfully destroyed.' }
     #format.json { head :no_content }
    #end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_info
      @user_info = UserInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_info_params
      params.require(:user_info).permit(:first_name, :last_name, :phone, :city, :state,:user_id,:account, :image)
    end
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/user_infos/_form.html.erb
<%= form_for(@user_info) do |f| %>
<%= form_for @user_info,:html => {:multipart => true} do |f| %>
    <% if @user_info.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user_info.errors.count, "error") %> prohibited this user_info from being saved:</h2>
  
        <ul>
        <% @user_info.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    
    


<div class="col-md-9 col-md-offset-1">

    <table class="table table-striped containe   text-left   " >
              
              <tr>
                <td>
                  <div class="field">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name ,class:"form-control"%>
                  </div>
                </td>        
                  
                  
                <td>
                  <div class="field">
                    <%= f.label :last_name %>
                    <%= f.text_field :last_name ,class:"form-control"%>
                  </div>
                </td>
              </tr>         
              
              <tr>
                
                
                <td>         
                  <div class="field">
                    <%= f.label :phone %>
                    <%= f.text_field :phone,class:"form-control" %>
                  </div>
                </td>
              </tr>
              
              <tr>
                <td>         
                  <div class="field">
                    <%= f.label :city %>
                    <%= f.text_field :city,class:"form-control" %>
                  </div>
                </td>
                
                <td>           
                  <div class="field">
                    <%= f.label :state %>
                    <%= f.text_field :state,class:"form-control" %>
                  </div>
                </td>
              </tr>
              
              
              
   <p>
     <%= f.file_field :image, onchange: "validateFiles(this);",
     data: { max_file_size: 5.megabytes } %>
   </p>
              
              <tr>
                <td>    
                  <div class="actions">
                    <%= f.submit 'Update', class:"btn btn-info  "%>
                    </div>
                </td>
              </tr>

    </table>
</div>

          <div class="field">
              <%=f.hidden_field :user_id, value: current_user.id %>
          </div>
<% end %>
<% end %>

app/views/user_infos/edit.html.erb
<h1>Editing User Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_info %> |
<%= link_to 'Back', user_infos_path %>

app/views/user_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Infos</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Street</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_infos.each do |user_info| %>
      <tr>
        <td><%= user_info.first_name %></td>
        <td><%= user_info.last_name %></td>
        <td><%= user_info.phone %></td>
        <td><%= user_info.city %></td>
        <td><%= user_info.state %></td>
        <td><%= user_info.user_id %></td>
        <td><%= link_to 'Show', user_info %></td>
        <td><%= link_to 'Edit', edit_user_info_path(user_info) %></td>
        <td><%= link_to 'Destroy', user_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User info', new_user_info_path %>

app/views/user_infos/new.html.erb
<h1>New User Info</h1>

<%= render 'form' %>

<%= link_to 'Back', user_infos_path %>

app/views/user_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  
<strong>Person Picture:</strong><br>
  <%= image_tag @user_info.image_url(:thumb), class:"img-thumbnail" if @user_info.image? %>
  
</p>

<p>
  <strong>First name:</strong>
  <%= @user_info.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user_info.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_info.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user_info.phone %>
</p>

<p>
  <strong>City:</strong>
  <%= @user_info.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user_info.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @user_info.zip_code %>
</p>

<p>
  <strong>Street:</strong>
  <%= @user_info.street %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_info.user_id %>
</p>

<%= link_to 'Edit', edit_user_info_path(@user_info) %> |
<%= link_to 'Back', user_infos_path %>