config/routes.rb
Rails.application.routes.draw do
  resources :atm_maches 
    resources :accounts,only: [:new,]
    resources :transactions
    resources :user_infos
     devise_for :users
      root 'atm_maches#index'
    resources :accounts do
      member do
        get :transaction_list
        get :select_transaction
        get :new_deposit
        post :create_deposit
        get :new_withdrawal
        post :create_withdrawal
      end
    end
        get 'page/home'
  
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :transactions
  
  attr_accessor :amount, :image, :name
  
  
  def deposit(i)
    t = (Time.now-6.hours).beginning_of_day 
    if i[:amount].to_f <= 0.0
      self.errors[:base] << " Negative OR empty NOT permited"
      puts " #{self.errors.full_messages.to_sentence} "
      return false
    else
      if ((Transaction.where("account_id =? and created_at>=? and debit=?",id,t,true).sum(:amount).to_f)+i[:amount].to_f) > 1000
        errors.add(:amount,"$1000.00 Daily Limited")        
        return false 
      else
        self.balance = balance.to_f + i[:amount].to_f
        self.save        
        return true
      end
    end
  end
  
  def withdrawal(i)
    t = (Time.now-6.hours).beginning_of_day
    if i[:amount].to_f <= 0.0 
      errors.add(:amount, " Negative OR Empty NOT Permited ")
      return false
    else
      if (self.balance.to_f  - i[:amount].to_f < 0.0 )
        errors.add(:CAN," ماكو هيج بطه تلعب شناو      ")                   #NO WITHDRAWAL MORE THAN THE AVAILABLE BALANCE
        return false
      else
        if ((Transaction.where("account_id =? and created_at>=? and debit=?",id,t,false).sum(:amount).to_f)+i[:amount].to_f) > 500
          errors.add(:YOU," $500.00 Daily Withdrawal limit")        
          return false
        else
          self.balance = balance.to_f - i[:amount].to_f
          self.save
          # transactions.create!(amount: i[:amount].to_f ,debit: false,account_id: id) we used anothe create in the controller
          return true
        end
      end
    end
  end
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
 before_action :set_account, only: [:show, :edit, :update, :destroy]
  
  
  def show
     session[:atm_no] = @atm_mach.id

  end
  def new_deposit
    @account = Account.find(params[:id])
  end
  def create_deposit
    
    @account = Account.find(params[:id])
    if deposit_params[:amount].to_f > 1000
      flash.alert = "Deposit more than a thousand in same day is not allowed "
      render :new_deposit
    else
      if @account.deposit(deposit_params)
        flash[:notice] = "Transaction completed Successfully"
        
        Transaction.create!(amount: deposit_params[:amount] , debit: true ,account_id: @account.id, atm_mach_id: session[:atm_no])
        redirect_to  atm_mach_path(session[:atm_no])
      else
        flash.alert = @account.errors.full_messages.to_sentence
        render :new_deposit
      end
    end
  end
    
  def new_withdrawal
    @account = Account.find(params[:id])
  end
  def create_withdrawal
    @account = Account.find(params[:id])
    if  withdrawal_params[:amount].to_f> 500
      flash.alert = "Daily Withdrawal Limit $500  "
      render :new_withdrawal
    else
      if @account.withdrawal(withdrawal_params)
        flash[:notice] = "Transaction completed Successfully"
        
        Transaction.create!(amount: deposit_params[:amount] , debit: false ,account_id: @account.id, atm_mach_id: session[:atm_no])
       
        redirect_to atm_mach_path(session[:atm_no])
      else
        flash.alert = @account.errors.full_messages.to_sentence
        render :new_withdrawal
      end
    end
  end
  
  def select_transaction 
  end

  def transaction_list
    @account = Account.find(params[:id])
    @transactions = @account.transactions
    pdf = TransactionsList.new(@transactions)
    respond_to do |format|
      format.html
      format.pdf do
        send_data pdf.render , filename: 'transactions_list.pdf', type:'application/pdf', disposition: "inline"
      end
    end
  end
  
  def index
    @accounts = Account.all
  end
  
  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end
  
  # GET /accounts/new
  def new
    @account = Account.new
    session[:atm_no] = params[:atm_no] 
  end
  
  # GET /accounts/1/edit
  def edit
    session[:atm_no] = params[:atm_no] 
  end
  
  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @atm_no = params[:atm_no] 
    respond_to do |format|
      if @account.save
        format.html { redirect_to atm_mach_path(session[:atm_no])}
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to edit_user_info_path(session[:user_info_no]) }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: ' Successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    def user_is_admin
      unless current_user.admin
        flash[:error] = "NO privileged to access this page"
        redirect_to root_path
      end
    end
  
  
  def set_account
    @account = Account.find(params[:id])
  end
  
  
  def account_params
    params.require(:account).permit(:balance, :account_number, :user_id, :active)
  end
  
  def deposit_params
    params.require(:account).permit(:amount)
  end
  
  def withdrawal_params
    params.require(:account).permit(:amount)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
        <% @account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3 col-md-offset-4 text-center " style="margin-top:90px">
      <h3><strong>Your initial balance is <%= number_to_currency( @account.balance)%></strong></h3></br>
      <div class="field">
        <%= f.hidden_field :balance %><br>
      </div>
      <div class="field">
        <%= f.hidden_field :user_id,value: current_user.id %><br>
      </div>
      <div class="field">
        <%= f.hidden_field :active,value: true %><br>
      </div>
      <div class="actions">
        <%= f.submit 'Create', class:"btn btn-info btn-lg"%>
      </div>
    </div>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Accounts</h1>
<table>
  <thead>
    <tr>
      <th>Balance</th>
      <th>Account number</th>
      <th>User</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.balance %></td>
        <td><%= account.account_number %></td>
        <td><%= account.user_id %></td>
        <!-- starting changing the true to OPEN-->
        <% if  account.active == true   %>
          <td><strong>Open</strong></td>
        <% else %>
          <td><strong>Closed</strong></td>
        <%end%>
        <!-- End of the status changing -->
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table><br>
<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/new_deposit.html.erb
<div class="row">
    <div class="col-md-3 col-md-offset-4 text-center " style="margin-top:140px">
            
            <%= form_for @account, url: create_deposit_account_path, method: :post do |f| %>
            
                 
             <div class="field">
                <h3><%= f.label :amount %></h3><br>
                <%= f.text_field :amount,class:"form-control input-lg text-center", placeholder:"Enter the amount here" %>
              </div><br>
              
              <div class="actions">
                <%=link_to 'Back', atm_mach_path(session[:atm_no]),class:"btn btn-danger btn-lg"%>&nbsp;&nbsp;
                <%= f.submit 'Deposit', class:"btn btn-info btn-lg"%>
              </div>
            
            <% end %>
            
    </div>
</div>

app/views/accounts/new_withdrawal.html.erb
<div class="row">
    <div class="col-md-3 col-md-offset-4 text-center " style="margin-top:140px">
        <%= form_for  @account, :url => create_withdrawal_account_path, method: :post do |f| %>
    
                <div class="field">
                   <h3> <%= f.label :amount %></h3><br>
                    <%= f.text_field :amount,class:"form-control input-lg text-center", placeholder:"Enter the amount here"%>
                </div><br>
              
                
                
                     <%= f.submit 'Withdrawal',class:"btn btn-danger btn-lg"%> &nbsp;&nbsp;
                     <%=link_to 'Back', atm_mach_path(session[:atm_no]),class:"btn btn-info btn-lg"%>
                   
                    
            
            
            <% end %>
    </div>
</div>

app/views/accounts/select_transaction.html.erb
</br></br><br>
    <table  class="table table-striped containe  text-center ">
        
        <tbody>
        
        
                      
                 <tr>
                        <td>
                              <%=link_to 'Deposit Transaction',  new_deposit_account_path ,class:"btn btn-success"%>
                        </td>
          
                        <td>
                              <%=link_to 'Withdrawal Transaction', new_withdrawal_account_path,class:"btn btn-danger"%>
                        </td>
                 </tr>
                      
               
        </tbody>
        
    </table></br>
<%=link_to'Back',atm_mach_path(session[:atm_no]),class:"btn btn-info" %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p><strong>Balance:</strong><%= @account.balance %></p>
<p><strong>Account number:</strong><%= @account.account_number %></p>
<p><strong>User:</strong><%= @account.user_id %></p>


<p><strong>Active:</strong>
<!-- starting changing the true to OPEN-->
<% if  @account.active == true   %><strong>Open</strong><% else %><strong>Closed</strong><%end%>
<!-- End of the status changing -->
</p>


<%= link_to 'New transaction' ,  new_transaction_path%> |<%= link_to 'Close the account' %>
</br>

<!-- Showing the account details  -->
<table>
    <tr>
        <td><strong>Account balance </strong><%= @account.balance %></td>
        <td> <strong>Account creation Date</strong><%= @account.created_at %></td>
        <td><strong>Account last update</strong><%= @account.updated_at %></td>
    </tr>
</table><hr>
 <!-- End showing Account details -->



<!-- Start Showing all the transactions Log -->
<strong> Transactions List</strong>

<p>
<table>
      <tr >
      <td>Amount</td>
      <td>Merchent name</td>
      <td>Transaction Time</td>
      <td>Transaction Type</td>
    </tr>
  
<% @account.transactions.each do |count|%>
  <tr>
      <td><%= count.amount%></td>

      <td><%= count.created_at%></td>
      <td><%= count.debit%></td>
  </tr>
<% end %>
  
</table>
</p>

<!-- End of showing the transactions Log  -->




<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/transaction_list.html.erb
<div class="row">
  <div class="col-md-12 col-md-offset-0 ">
    <br><h3>All transactions</h3><br>
    <table  class="table table-bordered table-responsive text-center">
    
   <p><%=link_to " PDF Transactions list", transaction_list_account_path(format: 'pdf'),class:"btn btn-info "%></p> 
        <tbody>
          <tr style="font-weight:bold">
            <td> ATM LOCATION</td>
            <td>TRANSACTION No.</td>
            <td> AMOUNT</td>
            <td> TYPE</td>
            <td> TIME</td>
          </tr>
            <% @transactions.each do |tran| %>
            <tr>
           <td>  <%=tran.atm_mach.address%></td>
              <td>
                <%= tran.id%>
              </td>
              <td>
                <%= number_to_currency(tran.amount) %>
              </td>
              <td>
                <% if tran.debit%>
                  <p style="color:blue"> Debit</p>
                <%else%>
                  <p  style="color:red"> Withdrawal</p>
                <%end%>
              </td>
              <td>
                <% t=tran.created_at%>
                <%= t.strftime("%I:%M:%S %p --- %m/%d/%Y")%>
              </td>
            </tr> 
          <%end%>
        </tbody>
   
    </table>
    <%=link_to 'Back', atm_mach_path(session[:atm_no]),class:"btn btn-danger btn-lg"%>
    <br>
  </div>
</div>
<!--  <p><%=link_to " PDF Transactions list", transaction_list_account_path(format: 'pdf'),class:"btn btn-info "%></p> --> 